server.port=8083

# SQLite Core Configuration
spring.datasource.url=jdbc:sqlite:desk2dine.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate 7 Official Community Dialect Bridge
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true